#!/bin/bash

#
# Put this at /usr/local/bin/drush to make "drush" command
# redirect to ddev drush.
#

set -e
#env
echo "PWD: $(pwd)"

if [[ -n "$SITE_ROOT" ]]; then

  echo "Site root: $SITE_ROOT"
  cd $SITE_ROOT

fi
ddev drush "${@}"
