#!/usr/bin/env bash

## Description: Import the live database and prepare this replica.
## Usage: sync
## Example: ddev sync

set -e

export PATH="vendor/bin:bin:$PATH"

echo "Sync the newnew."

echo "Hostname: $(hostname -f)"
echo "Whoami: $(whoami)"
echo "PWD: $(pwd)"

ddev drush status
echo ""
echo "I am about to destroy the site listed above."
echo "Hit CTRL-C within the next 3 seconds to abort..."
sleep 3

echo "> drush sql:drop"
ddev drush sql:drop --yes

# If database snapshot exists:
BACKUP_FILE=${BACKUP_FILE:-"~/Backups/newnew.page/live/snapshot.sql.gz"}
if [[ -f $BACKUP_FILE ]]; then
  ddev import-db --file $BACKUP_FILE
else
  echo "Database backup file $BACKUP_FILE not found. Create the file or set BACKUP_FILE environment variable to a new path."
  exit 1
fi

# @TODO:
#  Use ENV vars and .env file for configuring paths.
#  If on live server, create new backup.
#  If on local, download new backup.

echo
echo "> ddev drush deploy."
ddev drush deploy

echo
echo "> ddev drush en stage_file_proxy devel"
ddev drush en stage_file_proxy devel --yes

echo
echo "> drush status"
ddev drush status

echo
echo "Sync complete! Run 'ddev launch' to open the site in a browser, or 'ddev drush uli' to get a login link."
