_core:
  default_config_hash: RGedRkFydKZjS0ZJ6vbtZH00KbhYVGsK-ABILHdQLyw
prompt_logging: false
prompt_logging_tags: ''
default_providers:
  chat:
    provider_id: anthropic
    model_id: claude-3-5-sonnet-latest
  chat_with_complex_json:
    provider_id: anthropic
    model_id: claude-3-5-sonnet-latest
  chat_with_image_vision:
    provider_id: anthropic
    model_id: claude-3-5-sonnet-latest
