_core:
  default_config_hash: fl7YgLOjlmkovo0SEeKA1hldibx0fmdZ1VPUzWQVIwM
agent_settings:
  node_content_type_agent:
    usage_instructions: ''
    permissions:
      authenticated: 0
      content_editor: 0
      administrator: 0
    plugin_settings: {  }
