_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: c608f611-d2bc-487d-88d9-8c28366266a2
name: newnew.page
mail: no-reply@newnew.page
slogan: 'Newburgh / New Windsor Arts, Culture & Music'
page:
  403: /user/login
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
