name: Backup Data

on:
  workflow_dispatch:
  push:
    branches:
      - data-backups
  schedule:
    - cron: "5 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  backup:
    name: Backup data
    runs-on: craftysquirrels@server.craftysquirrels.com

    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: live
            path: "~/Sites/${{ github.repository }}/live"
            backup_path: "~/Backups/${{ github.repository }}"
            file: "snapshot.live.sql.gz"

          - environment: dev
            path: "~/Sites/${{ github.repository }}/dev"
            backup_path: "~/Backups/${{ github.repository }}"
            file: "snapshot.dev.sql.gz"
                        
    steps:
      - name: Status
        run: |
          cd  ${{ matrix.path }}
          echo "## ddev status"  >> $GITHUB_STEP_SUMMARY
          echo "```"  >> $GITHUB_STEP_SUMMARY
          ddev status  >> $GITHUB_STEP_SUMMARY
          echo "```"  >> $GITHUB_STEP_SUMMARY 
          
          echo "## drush status"  >> $GITHUB_STEP_SUMMARY
          echo "```"  >> $GITHUB_STEP_SUMMARY
          ddev drush status  >> $GITHUB_STEP_SUMMARY
          echo "```"  >> $GITHUB_STEP_SUMMARY      
          
      - name: Save Snapshot
        run: |
          cd  ${{ matrix.path }}
          mkdir -p ${{ matrix.backup_path }}/${{ matrix.file }}
          ddev export-db --file ${{ matrix.file }}
          ls -la ${{ matrix.file }}

