name: Pull Request Environment

on: 
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  DDEV_PROJECT_DOMAIN: pr${{ github.event.number }}.dev.newnew.page
  DDEV_PROJECT_PATH: "Sites/${{ github.repository }}/pr${{ github.event.number }}"

jobs:
  deploy:
    name: Deploy Site
    runs-on: craftysquirrels@server.craftysquirrels.com
    environment:
      name: pr${{ github.event.number }}
      url: http://${{ env.DDEV_PROJECT_DOMAIN }}?${{ github.run_id }}
    steps:

      - name: Deploy site
        uses: operations-platform/ddev-site@main
        with:
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          sync: "${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'rebuild') }}"
          sync-command: ddev sync
          ddev-fqdns: ${{ env.DDEV_PROJECT_DOMAIN }}
