name: Pull Request Comments

on:
  issue_comment:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  DDEV_SYNC_OPTIONS: ${{ contains(github.event.pull_request.labels.*.name, 'skip-update') && '--skip-update' }}

jobs:
  debug:
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  resync:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '#sync') }}
    runs-on: ubuntu-latest
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
