name: Pull Request Environment

on:
  workflow_dispatch:
    inputs:
      sync:
        description: "Sync site data"
        type: boolean
      pr_number:
        description: "PR Number"
        type: number
        required: true
  pull_request:
    types: [opened, reopened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ inputs.pr_number || github.event.number }}
  cancel-in-progress: true

env:
  DDEV_PROJECT_DOMAIN: pr${{ inputs.pr_number || github.event.number }}.dev.newnew.page
  DDEV_PROJECT_PATH: "Sites/${{ github.repository }}/pr${{ inputs.pr_number || github.event.number }}"

  # If label "rebuild", sync the site.
  ## Sync if workflow sync input or label.
  DDEV_REBUILD: ${{ inputs.sync || contains(github.event.pull_request.labels.*.name, 'rebuild') }}

  # If label "skip-update", use --skip-update
  DDEV_SYNC_OPTIONS: ${{ contains(github.event.pull_request.labels.*.name, 'skip-update') && '--skip-update' }}

jobs:
  deploy:
    name: Deploy Site
    runs-on: craftysquirrels@server.craftysquirrels.com
    if: ${{ inputs.sync || contains(github.event.pull_request.labels.*.name, 'preview-environment') }}
    environment:
      name: pr${{ inputs.pr_number || github.event.number }}
      url: http://${{ env.DDEV_PROJECT_DOMAIN }}?${{ github.run_id }}
    steps:

      - name: Deploy site
        uses: operations-platform/ddev-site@main
        with:
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Sync unless pr has "skip-sync" tag.
          sync: ${{ env.DDEV_REBUILD }}
          sync-command: ddev sync ${{ env.DDEV_SYNC_OPTIONS }}
          ddev-fqdns: ${{ env.DDEV_PROJECT_DOMAIN }}
          path: "Sites/${{ github.repository }}/pr${{ inputs.pr_number || github.event.number }}"
          git-reference: ${{ github.head_ref || github.ref_name }}
