name: Pull Request Environment

on:
  issue_comment:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  DDEV_PROJECT_DOMAIN: pr${{ github.event.number }}.dev.newnew.page
  DDEV_PROJECT_PATH: "Sites/${{ github.repository }}/pr${{ github.event.number }}"

  # If label "rebuild", sync the site.
  DDEV_REBUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild') }}

  # If label "skip-update", use --skip-update
  DDEV_SYNC_OPTIONS: ${{ contains(github.event.pull_request.labels.*.name, 'skip-update') && '--skip-update' }}

jobs:
  deploy:
    name: Deploy Site
    runs-on: craftysquirrels@server.craftysquirrels.com
    if: ${{ !github.event.issue.pull_request && contains(github.event.pull_request.labels.*.name, 'preview-environment') }}
    environment:
      name: pr${{ github.event.number }}
      url: http://${{ env.DDEV_PROJECT_DOMAIN }}?${{ github.run_id }}
    steps:

      - name: Deploy site
        uses: operations-platform/ddev-site@main
        with:
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Sync unless pr has "skip-sync" tag.
          sync: ${{ env.DDEV_REBUILD }}
          sync-command: ddev sync ${{ env.DDEV_SYNC_OPTIONS }}
          ddev-fqdns: ${{ env.DDEV_PROJECT_DOMAIN }}

  resync:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '#sync') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ~/$DDEV_PROJECT_PATH
          ddev sync $DDEV_SYNC_OPTIONS
