name: Pull Request Comments

on:
  issue_comment:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

env:
  DDEV_SYNC_OPTIONS: ${{ contains(github.event.issue.labels.*.name, 'skip-update') && '--skip-update' }}
  DDEV_PROJECT_PATH: "Sites/${{ github.repository }}/pr${{ github.event.issue.number }}"

jobs:
  resync:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '#sync') }}
    runs-on: craftysquirrels@server.craftysquirrels.com
    steps:

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Sync data
        run: |
          
          cd ~/$DDEV_PROJECT_PATH
          ddev sync $DDEV_SYNC_OPTIONS
